version: "3.5"
services:
  traefik:
    platform: linux/amd64
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    restart: unless-stopped
  redis:
    image: redis:alpine
    platform: linux/amd64
    expose:
      - "6379"
  mariadb:
    image: mariadb:10
    restart: always
    platform: linux/x86_64
    mem_limit: ${MEMORY_LIMIT_MYSQL:-1G}
    volumes:
      - ${PATH_DATA:-./data}/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"

  backend:
    image: nginx:alpine
    platform: linux/amd64
    working_dir: /application
    volumes:
      - ${BACKEND}:/application
      - ./docker/nginx-api/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
      - "443"
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.backend.rule=Host(`laravel.localhost`)"
      - "traefik.http.routers.backend.tls=false"

  php:
    platform: linux/amd64
    build:
      context: ./docker/php-fpm
      dockerfile: ./Dockerfile
      target: php8
    working_dir: /application
    volumes:
      - ${BACKEND}:/application
